name: llama-stack-trl-remote
distribution_spec:
  description: Llama Stack with Remote TRL Provider
  docker_image: null
  pip_dependencies:
    - llama-stack
    - opentelemetry-api
    - opentelemetry-sdk
    - opentelemetry-exporter-otlp
    - aiohttp
    - fastapi
    - uvicorn
    - trl==0.18.1
    - transformers==4.52.4
  providers:
    post_training:
      - remote::trl
    datasetio:
      - inline::localfs
apis:
  - post_training
  - datasetio
image_type: venv
image_name: trl-remote-client
external_providers_dir: ./providers.d 